---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-apps-huangxinzhong-com-v1-hxzdeployment
  failurePolicy: Fail
  name: mhxzdeployment.kb.io
  rules:
  - apiGroups:
    - apps.huangxinzhong.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - hxzdeployments
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-apps-huangxinzhong-com-v1-hxzdeployment
  failurePolicy: Fail
  name: vhxzdeployment.kb.io
  rules:
  - apiGroups:
    - apps.huangxinzhong.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - hxzdeployments
  sideEffects: None
