apiVersion: apps.huangxinzhong.com/v1
kind: HxzDeployment
metadata:
  labels:
    app.kubernetes.io/name: hxzdeployment
    app.kubernetes.io/instance: hxzdeployment-sample
    app.kubernetes.io/part-of: huangxinzhong-deployment
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: huangxinzhong-deployment
  name: hxzdeployment-sample
spec:
  # TODO(user): Add fields here
